# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Corne-ish Zen V2, Workman, invertedT, Mac, flip'
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right"]'
      alphas: '["workman"]'
      nav: '["invertedt"]'
      clipboard: '["mac"]'
      layers: '["flip"]'
